name: rec_mar
description: Recuerdalo Marco

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.6
  cloud_firestore: ^3.0.4
  flutter_launcher_icons: ^0.9.2
  dropdown_plus: ^0.0.9
  flutter_colorpicker: ^1.0.3
  speech_to_text: ^5.5.0
  flutter_picker: ^2.0.2
  flutter_tts: ^3.3.3
  rflutter_alert: ^2.0.4
  table_calendar: ^3.0.3
  any_link_preview: ^3.0.0
  awesome_notifications: ^0.6.21
  flutter_localizations:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon-app.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/backgrounds/
